apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/Test-Pool  # Update with your NFS share path
    server: 192.168.0.115         # Update with your TrueNAS server IP

