apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort  # Expose the service as a NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000  # Optional: Specify a NodePort or let Kubernetes assign one
  selector:
    app: nginx
